// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package simpleshop

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

type Item struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Weight      float64       `json:"weight"`
	Volume      float64       `json:"volume"`
	Stock       int32         `json:"stock"`
	Price       int32         `json:"price"`
	CreatedAt   time.Time     `json:"created_at"`
	CategoryID  sql.NullInt32 `json:"category_id"`
}

type ItemOrder struct {
	ID        int64   `json:"id"`
	OrderID   int32   `json:"order_id"`
	ItemID    int32   `json:"item_id"`
	Quantity  int32   `json:"quantity"`
	SubTotal  int32   `json:"sub_total"`
	SubWeight float64 `json:"sub_weight"`
}

type Order struct {
	ID           int64           `json:"id"`
	BuyerID      sql.NullInt32   `json:"buyer_id"`
	TotalPrice   sql.NullInt32   `json:"total_price"`
	TotalWeight  sql.NullFloat64 `json:"total_weight"`
	ShipmentCost sql.NullInt32   `json:"shipment_cost"`
}

type Profile struct {
	ID        int64          `json:"id"`
	UserBio   sql.NullString `json:"user_bio"`
	Email     sql.NullString `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID        int64         `json:"id"`
	Username  string        `json:"username"`
	Password  string        `json:"password"`
	Salt      string        `json:"salt"`
	CreatedAt time.Time     `json:"created_at"`
	Role      string        `json:"role"`
	ProfileID sql.NullInt32 `json:"profile_id"`
}
